# 程序运行时间
runtime: {
  from: '00:00',
  to: '24:00'
}

account: {
   username: "",
   password: "",
   type: ""
}

jobs: [
  {
    # 'job_name':  'bj -> sz',  # 任务名称，不填默认会以车站名命名，不可重复
    key: 0,

    # 任务
    # start_time 开始时间
    # seats 可用值: 特等座, 商务座, 一等座, 二等座, 软卧, 硬卧, 动卧, 软座, 硬座, 无座
    # from: to 从哪里到哪里
    # train_code 筛选车次 可以为空，为空则所有车次都可以提交 如 [] 注意大小写需要保持一致
    job: [
      { start_time: "2022-11-19",from: '北京',to: '驻马店',seats: [ '硬卧' ],train_code: [ "K157" ] },
    ],

    # 是否允许余票不足时提交部分乘客
    allow_less_member: false,

    # 乘客姓名，会根据当前账号自动识别乘客类型 购买儿童票 设置两个相同的姓名即可，程序会自动识别 如  ['张三', '张三']
    # "*王五", #在姓名前加*表示学生购买成人票
    # 7,  # 支持通过序号确定唯一乘客，序号查看可通过  python main.py -t 登录成功之后在 runtime/user/ 下找到对应的 用户名_passengers.json 文件，找到对应的 code 填入
    members: [
    ],
  }
]
